### ISSUE TITLE
TASCAM US-16x08 - Executable Binaries / Installable Packages

### ISSUE THREAD

**Issue by ZergeiW72** [onkelDead/tascam-driver-patch#4] opened 2019-06-16 12:44 UTC
Hi There ...

Could it be possible for you to provide me with executable binaries for all this TASCAM stuff ?
Especially tascam-gtk, tascam.lv2 and the tascam-driver-patch

Regards,
non-coder ZergeiW .

**Comment by rekado** [comment] 2020-08-04 14:18
You can install tascam-gtk with GNU Guix, a reproducible package manager for GNU+Linux distros.  You don't need the kernel patch with recent versions of the kernel Linux.

**Comment by lifeModder19135** [comment] 2021-09-25 02:44
@onkelDead  Was the patch accepted / integrated into alsa? If so, do you know the first compatible kernel version? I have a us-1641 that I am trying to repurpose for my daughter, and I am trying to resolve the shortest path to this end (something I am guessing you know a bit about, since you decided to go with the patch and not a driver.) I am hoping that I can find a 1608 driver and just change out the device #. I've done a bit of research, and as far as I can tell, the two required apis (the PCM signals) should be identical.

The 1608 was more or less a rebrand of the 1641 with a cosmetic makeover and an externalized power supply.  

Anyway, let me know if I can help with anything. I am good with about any Linux systems, although I specialize in the Debian based variety. I also have enough professional programming  experience that I don't want to specify in years, as it would age me.. XD

Regardless, thank you for your contribution to the human race. You successfully cut away another mile of weeds for me, and I will try to do the same for the mext guy or girl. They used to say that we are standing on the shoulders 
of giants. The way I see it, this has not been true for many years. Now we stand on the shoulders of each other.. regular sized people. But it makes no difference, because there are so many damned shoulders!

Once again, thank you.

**Comment by onkelDead** [comment] 2021-09-25 10:07
Hi,

reg. kernel version, its  4.11 which first contains the patch as reported in README.

I decided to go with a patch, cause the 1608 INs/OUTs worked properly out of the box without a patch, but alsa didn't offer mixer control elements for build-in EQs and compressors.
If I can help to clone/refactor the patch to fit for your 1641, please let me know.

Greets,
Onkel

**Comment by onkelDead** [comment] 2024-12-15 18:43
closed intentionally

**Closed as completed by onkelDead** 2024-12-15 18:43 UTC
